var ptoolsJsVersion="18.0",ol_width=300,ol_fgclass="overlibFGClass";YAHOO.namespace("ptools");[].indexOf||(Array.prototype.indexOf=function(a,b){for(var c=b||0;c<this.length;c++)if(this[c]==a)return c});function get_cookie(a){return(a=document.cookie.match("(^|;) ?"+a+"=([^;]*)(;|$)"))?unescape(a[2]):null}
function set_cookie(a,b,c,d,e,f){a=a+"="+escape(b);c&&(a+="; expires="+c.toGMTString());a=d?a+("; path= "+escape(d)):a+"; path= /";e&&(a+="; domain= "+escape(e));f&&(a+="; secure");document.cookie=a}function getElementsByClassNameNode(a,b){b||(b=document.getElementsByTagName("body")[0]);var c=[];if(b)for(var d=RegExp("\\b"+a+"\\b"),e=b.getElementsByTagName("*"),f=0;f<e.length;f++)e[f].className&&d.test(e[f].className)&&c.push(e[f]);return c}
function orgID(){var a=orgIDFromURL()||orgIDFromHostname()||basedOnforceOrgID()||getWindowOrgID()||get_cookie("recentOrgID0");return null!=a&&""!=a&&orgIDtoOrgStructure(a)?a:void 0!=window.preferred_database&&null!=preferred_database&&"none"!=preferred_database&&""!=preferred_database?preferred_database:defaultServerOrgID}
function orgIDFromURL(){for(var a=location.pathname.split("/"),b=0;b<a.length-1;b++){var c="string"==typeof a[b]?a[b].toUpperCase():"";if(orgNameFromOrgID(c))return c;if("METACYC"==c)return"META";if("ECOCYC"==c)return"ECOLI";if("HUMANCYC"==c)return"HUMAN";if("BSUBCYC"==c)return"BSUB"}if(1<location.search.length){a=location.search.slice(1).split("&");for(b=0;b<a.length;b++)if(c=a[b],0==c.search("orgid=")&&(c=c.slice(6).toUpperCase(),orgNameFromOrgID(c)))return c;for(b=0;b<a.length;b++)if(c=a[b],0==
c.search("object=")&&(c=c.slice(7).toUpperCase(),orgNameFromOrgID(c)))return c}return!1}function orgIDFromHostname(){var a=location.hostname.split(".");if(2<=a.length){var b=a[a.length-2].toUpperCase();"SRI"==b&&(b=a[Math.max(a.length-4,0)].toUpperCase());if("METACYC"==b)return"META";if("ECOCYC"==b)return"ECOLI";if("HUMANCYC"==b)return"HUMAN";if("BSUBCYC"==b)return"BSUB"}return!1}
function sriOrgDomain(){var a=location.hostname.split(".");return 2<=a.length&&(a=a[a.length-2].toUpperCase(),"SRI"==a||"METACYC"==a||"ECOCYC"==a||"HUMANCYC"==a||"BSUBCYC"==a||"BIOCYC"==a)?!0:!1}function orgIDtoSiteName(a){return"META"==a.toUpperCase()?"metacyc":"ECOLI"==a.toUpperCase()?"ecocyc":"HUMAN"==a.toUpperCase()?"humancyc":""}var forceOrgID;function bannerOrgID(){return forceOrgID||orgID()}function basedOnforceOrgID(){if(forceOrgID&&orgIDtoOrgStructure(forceOrgID))return forceOrgID}
function getOrgFullName(a){return orgNameFromOrgID(a)}var orgNameAssociativeArray=null,orgIdAssociativeArray=null;function buildOrgAssociativeArrays(){orgNameAssociativeArray=[];orgIdAssociativeArray=[];for(var a=0;a<allOrganisms.length;a++){var b=allOrganisms[a];orgNameAssociativeArray[b.label]=b;orgIdAssociativeArray[b.id]=b}}function orgIDtoOrgStructure(a){orgIdAssociativeArray||buildOrgAssociativeArrays();return orgIdAssociativeArray[a]}
function orgNameFromOrgID(a){a=orgIDtoOrgStructure(a);return null==a?"":a.label}function orgIDFromOrgName(a){orgNameAssociativeArray||buildOrgAssociativeArrays();if(a=orgNameAssociativeArray[a])return a.id}function isMultiOrgPGDB(){var a=orgIDtoOrgStructure(orgID());return null==a?!1:!0===a.multiorg}function isOrgidCelOverview(a){a=orgIDtoOrgStructure(a);return null==a?!0:!a.multiorg}function isOrgidRegOverview(a){a=orgIDtoOrgStructure(a);return null==a?!1:!0===a.regOv}
function isOrgidGenOverview(a){a=orgIDtoOrgStructure(a);return null==a?!1:!0===a.genOv}function isOrgidGenBrowser(a){a=orgIDtoOrgStructure(a);return null==a?!1:!0===a.genBrowser}
function adjustMenuItemsOrgID(a){for(var b=YAHOO.util.Dom.getElementsByClassName("orgspecific","a"),c=0;c<b.length;c++)b[c].href=b[c].href.replace("%5BORGID%5D",orgID()),b[c].href=b[c].href.replace("[ORGID]",orgID()),YAHOO.util.Dom.removeClass(b[c],"orgspecific");(b=YAHOO.widget.MenuManager.getMenuItem("regOVMenuItem"))&&b.cfg.setProperty("disabled",!isOrgidRegOverview(a));(b=YAHOO.widget.MenuManager.getMenuItem("genomeBrowserMenuItem"))&&b.cfg.setProperty("disabled",!isOrgidGenBrowser(a));(b=YAHOO.widget.MenuManager.getMenuItem("genOVMenuItem"))&&
b.cfg.setProperty("disabled",!isOrgidGenOverview(a));var b=YAHOO.widget.MenuManager.getMenuItem("cellOVMenuItem"),c=YAHOO.widget.MenuManager.getMenuItem("omicsMenuItem"),d=YAHOO.widget.MenuManager.getMenuItem("pwyEvMenuItem"),e=YAHOO.widget.MenuManager.getMenuItem("pwyHolesMenuItem"),f=YAHOO.widget.MenuManager.getMenuItem("blastMenuItem"),g=YAHOO.widget.MenuManager.getMenuItem("metEngMenuItem");isMultiOrgPGDB()?(b&&b.cfg.setProperty("disabled",!0),c&&c.cfg.setProperty("disabled",!0),d&&d.cfg.setProperty("disabled",
!0),e&&e.cfg.setProperty("disabled",!0),f&&f.cfg.setProperty("disabled",!0),g&&g.cfg.setProperty("disabled",!0)):(b&&b.cfg.setProperty("disabled",!1),c&&c.cfg.setProperty("disabled",!1),d&&d.cfg.setProperty("disabled",!1),e&&e.cfg.setProperty("disabled",!1),f&&f.cfg.setProperty("disabled",!1),g&&g.cfg.setProperty("disabled",!1));"ECOLI"==a&&(d.cfg.setProperty("disabled",!0),e.cfg.setProperty("disabled",!0))}
function updateOrgName(a){var b=getElementsByClassNameNode("dynDBName");if(b)for(var c=0;c<b.length;c++)b[c].innerHTML=getOrgFullName(a);adjustMenuItemsOrgID(a);userAdjustMenuItemsOrgID(a)}function updateBannerClass(a){var b=document.getElementsByTagName("body")[0];YAHOO.util.Dom.addClass(b,a)}
function get_browser_window_size(){var a=Array(2),b=100,c=100;-1!=navigator.appName.indexOf("Microsoft")&&document.documentElement?(c=document.documentElement.offsetHeight,b=document.documentElement.offsetWidth):-1!=navigator.appName.indexOf("Microsoft")&&document.body?(c=document.body.offsetHeight,b=document.body.offsetWidth):self.innerWidth?(b=self.innerWidth,c=self.innerHeight):document.documentElement&&document.documentElement.clientWidth?(b=document.documentElement.clientWidth,c=document.documentElement.clientHeight):
document.body?(b=document.body.clientWidth,c=document.body.clientHeight):alert("Cannot find frame window height and width");var d=document.getElementById("ptbanner"),e=d&&document.defaultView?document.defaultView.getComputedStyle(d,null):!1,d=e?parseInt(e.getPropertyValue("height")):d&&d.currentStyle?parseInt(d.currentStyle.height):0,f=(e=document.getElementById("pathwayToolsMenubar"))&&document.defaultView?document.defaultView.getComputedStyle(e,null):!1,e=f?parseInt(f.getPropertyValue("height")):
e&&e.currentStyle?parseInt(e.currentStyle.height):0,d=0<d?d:0,e=0<e?e:0;a[0]=Math.round(b);a[1]=Math.round(c-d-e);return a}function set_cookie_frame_dimension(){var a=get_browser_window_size(),b=new Date;b.setTime(b.getTime()+864E5);document.cookie="frameWidth="+a[0]+"; expires ="+b+"; path=/";document.cookie="frameHeight="+a[1]+"; expires ="+b+"; path=/"}
function initOnWindowLoad(){try{window.onresize=function(){set_cookie_frame_dimension()},userDefinedBeforePathwayToolsInit(),pathwayToolsInit(),userDefinedAfterPathwayToolsInit()}catch(a){alert(a)}}
function pathwayToolsInit(){var a=orgID();updateOrgName(a);updateBannerClass(bannerOrgID());getWindowOrgArray();var b=getWindowOrgID();b&&b==a||setWindowOrgID(a);get_cookie("recentOrgID0")!=a&&setRecentlyUsedCookie(a);1==allOrganisms.length&&cvtBannerToSingleOrg();void 0!=window.initLogin&&initLogin();set_cookie_frame_dimension();void 0!=window.dataSetsFreeForm&&0!=window.dataSetsFreeForm.length&&initSAQP();void 0!=window.SetPreviousValues&&SetPreviousValues();void 0!=window.tabberAutomatic&&tabberAutomatic();
void 0!=window.insertTemporaryMessage&&insertTemporaryMessage();insertRandomSelections();location.hash||document.getElementById("QSTextBox").focus();SVGInit()}function userDefinedBeforePathwayToolsInit(){}function userDefinedAfterPathwayToolsInit(){}function userAdjustMenuItemsOrgID(a){}function obfuscate(a,b,c,d){document.write('<a href="mailto:'+b+"@"+a+c+'">');""==d?document.write(b+"@"+a):document.write(d);document.write("</a>")}
function insertRandomSelections(){for(var a=getElementsByClassNameNode("randomDiv",null),b=0;b<a.length;b++)applyRandomSelection(a[b])}
function applyRandomSelection(a){if(a){for(var b=a.childNodes,c=null==b?0:b.length,d=0;d<c;d++)(a=b[d])&&a.style&&(a.style.width="0",a.style.display="none");a=[];for(d=0;d<c;d++){var e=b[d];e.innerHTML&&0<=e.innerHTML.search("[^ \n\t]")&&a.push(e)}b=a.length;0<b&&(c=(new Date).getSeconds(),b=Math.floor(Math.random(c)*b),a[b].style&&(a[b].style.width="100%",a[b].style.display="block"))}}var selectedOrgID;
function searchNamesAndTags(a,b){for(var c=[],d=decodeURI(a).toLowerCase(),e=0,f=b.length;e<f;e++){var g=b[e],h=g.label.toLowerCase();if(0===h.indexOf(d)||-1!=h.indexOf(" "+d))c[c.length]=g.label}c.sort(caseInsensitiveSortFn);this.responseSchema={fields:["label"]};return c}function caseInsensitiveSortFn(a,b){var c=a.toLowerCase(),d=b.toLowerCase();return c<d?-1:c>d?1:0}function caseInsensitiveOrgListSortByNameFn(a,b){var c=a.name.toLowerCase(),d=b.name.toLowerCase();return c<d?-1:c>d?1:0}
function organismSelectorAC(a,b,c,d){var e=new YAHOO.util.FunctionDataSource(function(a){return searchNamesAndTags(a,allOrganisms)}),f=new YAHOO.widget.AutoComplete(a,b,e);f.alwaysShowContainer=d?!1:!0;f.animVert=!1;f.autoHighlight=!1;f.typeAheadDelay=1;f.minQueryLength=0;f.maxResultsDisplayed=allOrganisms.length;d||f.sendQuery("");f.itemSelectEvent.subscribe(function(a,b){var d=b[1].innerHTML,e=YAHOO.util.Dom.get(c);e.innerHTML=d;e.value=orgIDFromOrgName(d)});f.dataRequestEvent.subscribe(function(a,
b){f.typeAhead=0<b[1].length});f.dataReturnEvent.subscribe(function(a,c){0==c[2].length?YAHOO.util.Dom.get(b).style.display="none":YAHOO.util.Dom.get(b).style.display="block";updateNumOrgs(c[2].length,c[1])});return{oDS:e,oAC:f}}
function populateQuickLinks(){for(var a=getRecentlyUsedCookies(),b=YAHOO.util.Dom.get("recentlyUsedContent"),c=0;c<a.length;c++)createQuicklink(b,a[c]);a=YAHOO.util.Dom.get("popularDatabasesContent");b=YAHOO.ptools.popularDatabases;if(0<b.length)for(c=0;c<b.length;c++)createQuicklink(a,b[c]);else YAHOO.util.Dom.get("popular").style.display="none";c=YAHOO.util.Dom.get("myPreferredContent");a=YAHOO.util.Dom.get("myPreferred");void 0!=window.preferred_database&&null!=preferred_database&&""!=preferred_database&&
"none"!=preferred_database&&createQuicklink(c,preferred_database)?a.style.display="block":a.style.display="none";YAHOO.util.Dom.get("setPreferredDiv").style.display=void 0!=window.preferred_database&&null!=preferred_database&&""!=preferred_database?"block":"none"}
function createQuicklink(a,b){var c=orgNameFromOrgID(b);if(c){var d=document.createElement("a");anchortext=document.createTextNode(c);d.appendChild(anchortext);d.setAttribute("href",'javascript:quickLinkClick("'+c+'")');a.appendChild(d);a.appendChild(document.createElement("br"));return d}return!1}
var onAlphabetListClick=new YAHOO.util.CustomEvent("onAlphabetListClick"),onQuickLinkClick=new YAHOO.util.CustomEvent("onQuickLinkClick"),fnSubscriberScroller=function(a,b){YAHOO.log(a);var c=b[0].letter;YAHOO.util.Dom.get("orgInput").value="";var d=YAHOO.util.Dom.get("orgContainer");d.childNodes[0].scrollTop=getPositionOfFirstEntryForLetter(c,d);YAHOO.log("success")},fnSubscriberQuicklink=function(a,b){YAHOO.log(a);var c=b[0];YAHOO.util.Dom.get("orgInput").value=c;YAHOO.util.Dom.get("orgInput2").innerHTML=
c;YAHOO.log("success")};function alphabetClick(a){onAlphabetListClick.fire({letter:a})}function quickLinkClick(a){onQuickLinkClick.fire(a)}function getPositionOfFirstEntryForLetter(a,b,c){a=indexOfFirstLetter(a,c);b=b.firstChild.firstChild.nextSibling.firstChild.firstChild;for(c=0;c<a;c++)b=b.nextSibling;return b.offsetTop}
function indexOfFirstLetter(a,b){b||(b=allOrganisms);a=a.toLowerCase();for(var c=b.length,d=0;d<c;d++)if(b[d].label.toLowerCase().charAt(0)==a||b[d].label.toLowerCase().charAt(0)>a)return d;return c-1}onAlphabetListClick.subscribe(fnSubscriberScroller);onQuickLinkClick.subscribe(fnSubscriberQuicklink);
function changeOrganism(){var a=YAHOO.util.Dom.get("orgInput").value;(selectedOrgID=orgIDFromOrgName(a))?YAHOO.util.Connect.asyncRequest("GET","/set-orgkb?kb="+selectedOrgID,{success:function(a){YAHOO.util.Dom.get("setPreferred").checked&&YAHOO.util.Connect.asyncRequest("GET","/ajax-set-one-preference?type=PREFERRED-DATABASE&object="+selectedOrgID);initChooser.continuation?(orgSelectorDialog.hide(),a=initChooser.continuation,initChooser.continuation=!1,a.call(null,selectedOrgID)):(setOrganism(selectedOrgID),
organismChangedEvent.fire(),orgSelectorDialog.hide(),document.location.href="/organism-summary?object="+selectedOrgID)},failure:function(a){alert("set-orgkb failed")}}):alert("Please select a valid organism")}function setOrganism(a){orgNameFromOrgID(a)&&(setRecentlyUsedCookie(a),YAHOO.ptools.currentOrgID=a,updateOrgName(a))}function getRecentlyUsedCookies(){var a=[],b,c;for(b=0;5>b;b++)(c=get_cookie("recentOrgID"+b))&&(a[a.length]=c);return a}
function setRecentlyUsedCookie(a){var b=0,c=a,d,e=get_cookie("recentOrgID"+b);for(set_cookie("recentOrgID0",a);e&&e!=a&&e!=c&&5>b;)b+=1,c=e,d="recentOrgID"+b,e=get_cookie(d),set_cookie(d,c);setWindowOrgID(a)}var windowOrgArray;function getWindowOrgArray(){windowOrgArray=[];var a=get_cookie("windowOrg");if(a)for(var a=a.split(":"),b=0;b<a.length;b+=2)windowOrgArray[windowOrgArray.length]={name:a[b],org:a[b+1]}}getWindowOrgArray();
function saveWindowOrgArray(){for(var a="",b=0,c=windowOrgArray.length-1;0<=c;c--){var d=windowOrgArray[c];d.name&&d.org&&10>b&&(a=d.name+":"+d.org+":"+a,b++)}set_cookie("windowOrg",a)}
function setWindowOrgID(a){getWindowOrgArray();if(window.name&&0!=window.name.length&&"_"!=window.name[0])if(getWindowOrgID())for(var b=0;b<windowOrgArray.length;b++)windowOrgArray[b].name==window.name&&(windowOrgArray[b].org=a);else windowOrgArray[windowOrgArray.length]={name:window.name,org:a};else window.name=getNewWindowName(),windowOrgArray[windowOrgArray.length]={name:window.name,org:a};saveWindowOrgArray()}
function getNewWindowName(){windowOrgArray||getWindowOrgArray();if(0<windowOrgArray.length){for(var a=0,b,c=!0;c;){b="ptools"+a;for(var d=!1,e=0;e<windowOrgArray.length;e++)windowOrgArray[e].name==b&&(d=!0);d||(c=!1);a++}return b}return"ptools0"}function getWindowOrgID(){if(usePopupChooser())return!1;var a=!1;if(window.name)for(var b=0;b<windowOrgArray.length;b++)windowOrgArray[b].name==window.name&&(a=windowOrgArray[b].org);return a&&orgNameFromOrgID(a)?a:!1}function usePopupChooser(){return!1}
var chooserInitialized=!1;function initChooser(){chooserInitialized||(loadChooser(),10>=allOrganisms.length?YAHOO.util.Dom.get("centercontent").style.visibility="hidden":updateNumOrgs(allOrganisms.length,""),populateQuickLinks(),organismSelectorAC("orgInput","orgContainer","orgInput2"),buildOrgSelectorTaxTree(),new YAHOO.widget.TabView("orgSelectorTabs"),chooserInitialized=!0)}
function loadChooser(){new Ajax.Updater("orgSelectorDialogCC","/org-chooser",{asynchronous:!1});var a=new YAHOO.util.KeyListener(document,{keys:13},{fn:changeOrganism});orgSelectorDialog=new YAHOO.widget.Dialog("orgSelectorDialog",{buttons:[{text:"OK",handler:function(){changeOrganism()},isDefault:!0},{text:"Cancel",handler:function(){this.cancel()}}],visible:!1,fixedcenter:!1,draggable:!0,dragOnly:!0,keylisteners:a,zIndex:1E3});orgSelectorDialog.width=820;orgSelectorDialog.render();orgSelectorDialog.center();
orgSelectorDialog.beforeShowEvent.subscribe(initChooser)}function updateNumOrgs(a,b,c){b=0<b.length?" matching ":" ";var d;0<=a&&(d=1==a?"1"+b+"database available":0==a?"No matching databases available":a+b+"databases available");document.getElementById(c?c:"orgnum").innerHTML='<br><div style="text-align:center">'+d+"</div>"}var chooserContinuation=!1,orgSelectorDialog;
function showChooser(a){initChooser();chooserContinuation=initChooser.continuation=a;usePopupChooser()?window.open("/chooser.shtml","remote","width=800,height=600"):(orgSelectorDialog.center(),orgSelectorDialog.show(),YAHOO.util.Dom.get("orgInput").focus())}
function buildOrgSelectorTaxTree(){var a=new YAHOO.widget.TreeView("orgSelectorTaxTree");a.setDynamicLoad(loadNCBISubclasses,1);var b=a.getRoot(),b=new YAHOO.widget.TextNode({id:"TAX-1",label:"All"},b,!1);a.subscribe("clickEvent",function(a){a=a.node;a.isLeaf&&(a=orgNameFromOrgID(a.data.id),YAHOO.util.Dom.get("orgInput").value=a,YAHOO.util.Dom.get("orgInput2").innerHTML=a);return!0});a.draw();b.expand();a.render();initTaxAC(a,"taxName","taxContainer","taxTabInterior")}
function loadNCBISubclasses(a,b){YAHOO.util.Connect.asyncRequest("GET","/ajax-pgdb-taxon-subs?object="+a.data.id,{success:function(b){var d=eval("("+b.responseText+")");if(d&&d.length&&YAHOO.lang.isArray(d))for(var e=0,f=d.length;e<f;e++){var g=d[e],h;h=new YAHOO.widget.TextNode(g,a,!1);h.data=g;h.title=g.doc;g.isClass?(h.label=g.label+" ("+g.numInstances+")",h.isLeaf=!1,h.enableHighlight=!1,("TAX-1"==a.data.id||a.data.singleChild)&&h.expand()):h.isLeaf=!0}b.argument.fnLoadComplete()},argument:{node:a,
fnLoadComplete:b},timeout:14E3})}function initTaxAC(a,b,c,d){var e=ACNameSelector(YAHOO.util.Dom.get(b),YAHOO.util.Dom.get(c),!1,"PGDB-TAXA").oAC;e.itemSelectEvent.subscribe(function(b,c){var h=c[2][0];YAHOO.util.Connect.asyncRequest("GET","/ajax-path-to-taxon?id="+h,{success:function(b){if(b=eval("("+b.responseText+")")){b[b.length-1]!=h&&(b[b.length]=h);var c=a.getRoot();expandTreePath(c,b,d);e.getInputEl().value=""}}})});e.forceSelection=!0}
function cvtBannerToSingleOrg(){for(var a=YAHOO.util.Dom.getElementsByClassName("withDatabase","div"),b=0;b<a.length;b++)YAHOO.util.Dom.removeClass(a[b],"withDatabase");a=YAHOO.util.Dom.getElementsByClassName("menuDatabase","table");for(b=0;b<a.length;b++)YAHOO.util.Dom.setStyle(a[b],"visibility","hidden");a=YAHOO.util.Dom.getElementsByClassName("searchMenuDatabaseName","div");for(b=0;b<a.length;b++)YAHOO.util.Dom.setStyle(a[b],"visibility","hidden")}function addSiteSpecificMenuItems(){}
function addContextSpecificToolbarMenus(){var a=getTypeObjectPage().gene,b=a?"gene":getTypeObjectPage().type,a=a?a:getTypeObjectPage().object||objectFrameIDFromURL(),b=stringTypeToType(b),c=orgID(),d=b+"Menu";"protein"!=b&&"enzyme"!=b||addProteinMenu(d,b,a,c);"pathway"==b&&addPathwayMenu(d,b,a,c);"transcription-units"==b&&"ECOLI"==c&&addOperonMenu(d,b,a,c);"reaction"==b&&addReactionAtomMappingMenu(d,a,c);document.getElementById("mapReg")&&addRegOvMenu();document.getElementById("mapCel")&&addCelOvMenu();
addSearchOtherDBsMenuCommand(d,b,a,c);"gene"==b&&addGeneMenu(d,a,c)}var defaultTypeObjectPage={object:"",orgid:"",type:"",biopax2:!1,biopax3:!1,gene:!1};function getTypeObjectPage(){return window.typeObjectPage||defaultTypeObjectPage}function recordPageTitle(a,b){window.typeObjectPage=getTypeObjectPage();window.typeObjectPage.prefix=a;window.typeObjectPage.title=b}
function addReactionAtomMappingMenu(a,b,c){createToolbarMenu(a,{text:"Reaction",submenu:{id:a,itemdata:[{url:"/"+c+"/download-atom-mappings?object="+b,text:"Download atom mapping(s) for this reaction"}]}},"objMenu")}function downloadReactionAtomMappings(a,b){YAHOO.util.Connect.asyncRequest("GET","/"+b+"/ajax-download-atom-mappings?object="+a,{success:function(a){a.responseText&&alert(a.responseText)}})}
function addRegOvMenu(){createToolbarMenu("regOverviewMenu",{text:"Regulatory&nbsp;Overview",submenu:{id:"regOverviewMenu",itemdata:[{text:"Overlay Experimental Data (Omics Viewer)",style:"EXPANDED",tooltip:"Color genes according to data imported from an omics dataset (such as a gene expression dataset). Multiple timepoints can be viewed as an animation.",submenu:{id:"regOmicsViewerMenu",itemdata:[{url:"javascript:omicsViewer(initRegOverview)",text:"Upload Data from File",tooltip:"Overlay data (such as gene expression data) by uploading a tab-delimited file, with gene names or ids in the first column, and data values in one or more subsequent columns."},
{url:"javascript:omicsViewer(initRegOverview,'PortEco')",text:"Import Data from PortEco",tooltip:"Search for gene expression datasets in PortEco that match some keyword for this organism (PortEco primarily contains E. coli datasets), and overlay the data on this diagram."},{url:"javascript:omicsViewer(initRegOverview, 'GEO')",text:"Import Data from GEO",tooltip:"Search for datasets in GEO (Gene Expression Omnibus) that match some keyword for this organism, and overlay the data on this diagram."},
{url:"javascript:omicsViewer(initRegOverview, 'cookie')",text:"From Recent Datasets (PortEco or GEO only)",tooltip:"Overlay data from a recently visited PortEco or GEO dataset. Because data from uploaded files is not stored on the server, this option is not available for recently uploaded files -- to avoid having to re-upload a file, try saving the data as a Group."},{url:"javascript:omicsViewer(initRegOverview, 'group')",text:"From Group",tooltip:"Overlay data from a recently visited Group that has genes in the first column, and data values in or or more subsequent columns.  Only groups visited in the current session are available for this option."}]}},
{text:"",classname:"spacer"},{text:"Change Layout",url:"javascript:regChangeLayoutShow()",tooltip:"Specify whether genes should be laid out as nested ellipses or from top to bottom (for Complete Regulatory Overview only)."},{text:"Redisplay Highlighted Genes Only",url:"javascript:regRedisplayHighlightedGenesOnly()",tooltip:"If you have highlighted one or more sets of genes, regenerate the diagram showing just those genes, in top-to-bottom format."},{text:"Redisplay Complete Regulatory Overview",url:"javascript:regDisplayCompleteOverview()",
tooltip:"If currently showing highlighted genes only, return to view that shows all genes."},{text:"",classname:"spacer"},{text:"Highlight Genes",style:"EXPANDED",submenu:{id:"highlightGenesMenu",itemdata:[{url:"javascript:showOvDialog(regDialogNameOrFrameID)",text:"Genes By Name or Frame ID"},{url:"javascript:showOvDialog(regDialogSubstring)",text:"Genes By Substring"},{url:"javascript:regInitDialogGeneOntology()",text:"Genes By Gene Ontology Terms"},{text:"Clear All Highlighting",url:"javascript:clearAllHighlightedGenes()"}]}},
{text:"",classname:"spacer"},{text:"Show Legend",url:"javascript:regDialogLegend.show()"},{text:"Help",url:"javascript:window.open('/PToolsWebsiteHowto.shtml#regOverview');void(0)"}]}},"objMenu")}
function addCelOvMenu(){createToolbarMenu("celOverviewMenu",{text:"Cellular&nbsp;Overview",submenu:{id:"celOverviewMenu",itemdata:[{text:"Overlay Experimental Data (Omics Viewer)",style:"EXPANDED",tooltip:"Color nodes and/or edges according to data imported from an omics dataset (such as a gene expression or metabolomics dataset). Multiple timepoints can be viewed as an animation (with graph of all timepoints in mouseovers).",submenu:{id:"omicsViewerMenu",itemdata:[{url:"javascript:omicsViewer(initCelOverview)",
text:"Upload Data from File",tooltip:"Overlay data (such as gene expression or metabolomics data) by uploading a tab-delimited file, with object names or ids in the first column, and data values in one or more subsequent columns."},{url:"javascript:omicsViewer(initCelOverview, 'PortEco')",text:"Import Data from PortEco",tooltip:"Search for gene expression datasets in PortEco that match some keyword for this organism (PortEco primarily contains E. coli datasets), and overlay the data on this diagram."},
{url:"javascript:omicsViewer(initCelOverview,'GEO')",text:"Import Data from GEO",tooltip:"Search for datasets in GEO (Gene Expression Omnibus) that match some keyword for this organism, and overlay the data on this diagram."},{url:"javascript:omicsViewer(initCelOverview, 'cookie')",text:"From Recent Datasets (PortEco or GEO only)",tooltip:"Overlay data from a recently visited PortEco or GEO dataset. Because data from uploaded files is not stored on the server, this option is not available for recently uploaded files -- to avoid having to re-upload a file, try saving the data as a Group."},
{url:"javascript:omicsViewer(initCelOverview, 'group')",text:"From Group",tooltip:"Overlay data from a recently visited Group that has objects (e.g. genes, compounds, reactions) in the first column, and data values in or or more subsequent columns.  Only groups visited in the current session are available for this option."}]}},{text:"",classname:"spacer"},{text:"Highlight",style:"EXPANDED",submenu:{id:"celHighlightMenu",itemdata:[{text:"Highlight Pathway(s)",submenu:{id:"celHighlightPathwaysMenu",
itemdata:[{url:"javascript:showOvDialog(celDialogPathwayNameOrFrameID)",text:"By Name or Frame ID"},{url:"javascript:showOvDialog(celDialogPathwaySubstring)",text:"By Substring"}]}},{text:"Highlight Reaction(s)",submenu:{id:"celHighlightReactionsMenu",itemdata:[{url:"javascript:showOvDialog(celDialogReactionNameOrFrameID)",text:"By Name or Frame ID"},{url:"javascript:showOvDialog(celDialogReactionSubstring)",text:"By Substring"},{url:"javascript:showOvDialog(celDialogReactionEC)",text:"By EC Number"},
{url:"javascript:showOvDialog(celDialogReactionEnzyme)",text:"By Enzyme Name"}]}},{text:"Highlight Gene(s)",submenu:{id:"celHighlightGenesMenu",itemdata:[{url:"javascript:showOvDialog(celDialogGeneNameOrFrameID)",text:"By Name or Frame ID"},{url:"javascript:showOvDialog(celDialogGeneSubstring)",text:"By Substring"},{url:"javascript:showOvDialog(celDialogGeneFile)",text:"From File"}]}},{text:"Highlight Enzyme(s)",submenu:{id:"celHighlightEnzymesMenu",itemdata:[{url:"javascript:showOvDialog(celDialogEnzymeNameOrFrameID)",
text:"By Name or Frame ID"},{url:"javascript:showOvDialog(celDialogEnzymeSubstring)",text:"By Substring"}]}},{text:"Highlight Compound(s)",submenu:{id:"celHighlightCompoundsMenu",itemdata:[{url:"javascript:showOvDialog(celDialogCompoundNameOrFrameID)",text:"By Name or Frame ID"},{url:"javascript:showOvDialog(celDialogCompoundSubstring)",text:"By Substring"}]}},{text:"Highlight/Omics View Based on Names and Frame IDs",url:"javascript:celDialogMixing.show()",tooltip:"Type or paste in a set of object names or ids to be highlighted.  If omics data is supplied for each object (optional), the omics viewer will be invoked."},
{text:"Clear All Highlighting",url:"javascript:clearAllHighlightingCel()"}]}},{text:"",classname:"spacer"},{text:"Show Legend",url:"javascript:showOvDialog(celDialogLegend)"},{text:"Generate Bookmark for Current Cellular Overview",url:"javascript: celDialogGenURL.show(); genCelURL();",tooltip:"Generate a url that can be bookmarked or shared that shows the overview in its current highlighting state.  Note that this applies only to basic highlight operations, not to omics data."},{text:"Help",url:"javascript:window.open('/PToolsWebsiteHowto.shtml#celOverview');void(0)"}]}},
"objMenu")}
function addPathwayMenu(a,b,c,d){var e=getTypeObjectPage();b=!e.biopax2;e=!e.biopax3;b=[{text:"Customize or Overlay Omics Data on Pathway Diagram",onclick:{fn:function(){window.name="main";var a="/"+d+"/customize-pwy?object="+c+"&"+location.search.substring(1);window.open(a,"remote","width=560,height=800,menubar=0,toolbar=0,location=0,directories=0,status=0,resizable=1")}},tooltip:"Pop up a control panel allowing the user to customize the pathway diagram to show/hide various elements, and/or upload a file of omics data and color the diagram accordingly.  There is also the option to generate a publication-quality postscript or pdf version of the diagram."},{text:"Download Genes",
url:"/"+d+"/pathway-genes?object="+c,tooltip:"Generate a textual table listing each gene in this pathway (id, name, accession) and the reaction it catalyzes."},{text:"BioPax Level 2",url:"/"+d+"/pathway-biopax?type=2&object="+c,disabled:b,tooltip:b?"This pathway is not available in BioPax Level 2 format because it includes some features that are not supported.":"Download this pathway as a BioPax Level 2 OWL file.  Note that identifiers are generated automatically for this file, so cannot be compared among different downloads.  To obtain a file containing all pathways (with consistent identifiers) in BioPax format, see the Downloads page."},
{text:"BioPax Level 3",url:"/"+d+"/pathway-biopax?type=3&object="+c,disabled:e,tooltip:e?"This pathway is not available in BioPax Level 3 format because it includes some features that are not supported.":"Download this pathway as a BioPax Level 3 OWL file.  Note that identifiers are generated automatically for this file, so cannot be compared among different downloads.  To obtain a file containing all pathways (with consistent identifiers) in BioPax format, see the Downloads page."}];"ECOLI"==d&&
(b=b.concat({text:"Export Genes to PortEco Cluster My Genes",url:xmlhttpGet("/apixml?fn=genes-of-pathway&id="+d+":"+c+"&detail=low",null,gotoPortEco,"t")}));createToolbarMenu(a,{text:"Pathway",submenu:{id:a,itemdata:b}},"objMenu")}function addOperonMenu(a,b,c,d){createToolbarMenu(a,{text:"Operon",submenu:{id:a,itemdata:[{text:"Export Genes to PortEco Cluster My Genes",url:xmlhttpGet("/apixml?fn=transcription-unit-genes&id="+d+":"+c+"&detail=low",null,gotoPortEco,"t")}]}},"objMenu")}
function gotoPortEco(a){var b;if("undefined"!=typeof window.DOMParser)b=function(a){return(new window.DOMParser).parseFromString(a,"text/xml")};else if("undefined"!=typeof window.ActiveXObject&&new window.ActiveXObject("Microsoft.XMLDOM"))b=function(a){var b=new window.ActiveXObject("Microsoft.XMLDOM");b.async="false";b.loadXML(a);return b};else throw Error("No XML parser found");a=b(a).documentElement;b="http://expression.porteco.org/cgi-bin/data/experimentGene.pl?";for(var c=1;c<a.childNodes.length;c+=
2)if("Gene"==a.childNodes[c].tagName)for(var d=a.childNodes[c],e=0;e<d.childNodes.length;e+=1)"common-name"==d.childNodes[e].tagName&&(b+="GeneId="+d.childNodes[e].textContent+";");return b}
function addShowInMetacyc(a,b,c,d){"META"!==orgID()&&YAHOO.util.Connect.asyncRequest("GET","/META/ajax-frame-exists-p?object="+b,{success:function(a){"T"==a.responseText&&addMenuOpToNavBox({text:c,url:"/META/new-image?object="+b,menuId:"compareOps",tooltip:"Navigate to the page for this object in the MetaCyc database, if it exists."})}})}function addProteinMenu(a,b,c,d){getTypeObjectPage().tf&&addMenuOpToNavBox({url:"/"+d+"/tf-binding-sites?object="+c,text:"Download Binding Sites"})}
function getScreenWidth(){var a=0;"number"==typeof window.innerWidth?a=window.innerWidth:document.documentElement&&document.documentElement.clientWidth?a=document.documentElement.clientWidth:document.body&&document.body.clientWidth&&(a=document.body.clientWidth);return a}
function addGeneMenu(a,b,c){var d=Math.floor(0.9*getScreenWidth()),e="javascript:goIfOrgsSelected('"+("/"+c+"/invoke-browse-orthologs?type=LOCUS-POSITION&object="+b)+"', navBoxMultiorgChooser)",f="javascript:goIfOrgsSelected('"+("/"+c+"/compare-frame-in-orgs?type=ORTHOLOG&object="+b+"&initial-orgs="+c)+"', navBoxMultiorgChooser)";a="javascript:goIfOrgsSelected('"+("/"+c+"/getalignment?width="+d.toString()+"&orthologs="+b+":"+c+"&type=nt")+"',  navBoxMultiorgChooser)";b="javascript:goIfOrgsSelected('"+
("/"+c+"/getalignment?width="+d.toString()+"&orthologs="+b+":"+c+"&type=pep")+"',  navBoxMultiorgChooser)";1<allOrganisms.length&&isOrgidGenBrowser(c)&&(c=[{text:"Show orthologs (with operon diagrams) in multiple databases",url:f,tooltip:"Generate a table listing this gene and its orthologs in the selected organism databases, showing gene products and operon organization."},{text:"Align in Multi-Genome Browser",url:e,tooltip:"Show this gene, along with its orthologs in the selected organism databases, in the Multi-Genome Browser"}],
sriOrgDomain()&&(c.push({text:"Align gene nucleotide sequence with orthologs",url:a,tooltip:"Show this gene's nucleotide sequence aligned with its orthologs in the selected organism databases."}),c.push({text:"Align gene product amino acid sequence with orthologs",url:b,tooltip:"Show this gene product's amino acid sequence aligned with its orthologs in the selected organism databases."})),addMenuOpToNavBox({text:"Comparison Operations",id:"compareOps",submenu:{itemdata:c}}))}
function stringTypeToType(a){if("string"!=typeof a)return"";a=a.toLowerCase();for(var b="compound gene pathway protein enzyme reaction transcription-units class".split(" "),c=0;c<b.length;c++)if(0<=a.indexOf(b[c]))return b[c];return""}var urlSearchAll;function showInSelectedDBs(){goIfOrgsSelected(urlSearchAll,navBoxMultiorgChooser)}
function addSearchOtherDBsMenuCommand(a,b,c,d){if(null!=c&&null!=d&&1<allOrganisms.length&&("compound"==b||"reaction"==b||"gene"==b||"pathway"==b||"protein"==b||"enzyme"==b)){var e="enzyme"==b?"protein":b,f=e.substring(0,1).toUpperCase()+e.substring(1).toLowerCase(),g="Search for this "+e+" in other databases",h="Select a set of organisms to search, and generate a table of links to this "+e+" in all of those organisms in which it was found.";"gene"==b&&(h+=" Searching is by both ortholog and gene name.");
var k="Show this "+e+" in another database",e="Select a different organism database, and open a new tab showing the page for this "+e+" (if it exists) in that database";urlSearchAll=showAllQueryString(b,c,d);addMenuOpToNavBox({text:"Comparison Operations",id:"compareOps",submenu:{itemdata:[{url:"javascript:showChooser(function(selectedOrgID){window.open(queryShowString(selectedOrgID,'"+b+"','"+d+"','"+c+"','"+f+"'))})",text:k,tooltip:e},{url:"javascript:navBoxMultiorgChooser()",text:"Change organisms/databases for comparison operations",
tooltip:"Change the set of organism databases to be used for subsequent searching and comparison operations."},{url:"javascript:showInSelectedDBs()",text:g,tooltip:h}]}})}"compound"!=b&&"reaction"!=b&&"pathway"!=b&&"class"!=b||addShowInMetacyc(a,c,"Show this "+b+" in MetaCyc",a)}
function navBoxMultiorgChooser(){var a=getTypeObjectPage().gene;a?getPresentOrgidsAndShowChooser(a,"ORTHOLOG",orgID(),!0,"Organisms in which an ortholog for this gene has been identified are shown in bold."):showMultiorgChooser()}
function showWaitMsg(a,b,c){var d=null,e=function(){var b=new YAHOO.widget.Dialog("waitMsg",{width:"40em",fixedcenter:!0,modal:!0,visible:!0,draggable:!0,buttons:[{text:"Cancel Operation",handler:function(){b.hide();c&&c()},isDefault:!1}]});d=b;b.setHeader("Wait For Operation to Complete");b.setBody(a);b.cfg.setProperty("icon",YAHOO.widget.Dialog.ICON_WARN);b.render(document.body)},f=window.setTimeout(function(){e()},1E3*b);return function(){f&&clearTimeout(f);d&&d.hide()}}
function showAllQueryString(a,b,c){return"/"+c+"/show-in-other-dbs?type="+a.toUpperCase()+"&object="+encodeURIComponent(b)}
function queryShowString(a,b,c,d,e){return"compound"==b||"reaction"==b||"pathway"==b?"/query?submit=Submit+Query&object="+encodeURIComponent('("HTML-CUSTOM" "html-table-headers('+("["+a+'~\\"'+d+'\\":'+a+'~\\"'+d+'\\"]')+',(\\"'+e+'\\"),\\"show-sole-result\\")")'):"/query?submit=Submit+Query&object="+encodeURIComponent('("HTML-CUSTOM" "html-table-headers([r:l1:=find-objects(\\"'+a+'\\",'+c+'~\\"'+d+'\\"),l2:=find-orthologs(\\"'+a+'\\",'+c+'~\\"'+d+'\\"),both:=l1**l2,ort:=l2 -- both,sim:=l1 -- both,r<-[(database(r),r,r^'+
getOutputSlotName(b)+',\\"Same name/synonym\\"):r<-sim]++[(database(r),r,r^'+getOutputSlotName(b)+',\\"Ortholog\\"):r<-ort]++[(database(r),r,r^'+getOutputSlotName(b)+',\\"Same name/synonym and ortholog\\"):r<-both]],(\\"Organism (Database)\\",\\"'+e+'\\",\\"'+getOutputSlotName(b)+'\\",\\"Found Based On\\"),\\"show-sole-result\\")")')}
function getOutputSlotName(a){return"gene"==a?"Product":"compound"==a?"Chemical-formula":"pathway"==a?"Reaction-list":"reaction"==a?"EC-number":"protein"==a?"Gene":"enzyme"==a?"Gene":"name"}function objectFrameIDFromURL(){var a=location.pathname,a=0<=a.indexOf("new-image")||0<=a.indexOf("NEW-IMAGE"),b=getArgs();return a&&void 0!=b.object?b.object:null}
function createToolbarMenu(a,b,c,d){var e=YAHOO.widget.MenuManager,f=e.getMenu(a);f?b.submenu&&f.addItems(b.submenu.itemdata):d?(f=e.getMenu("pathwayToolsMenubar"),f.addItem(b),c&&(a=e.getMenu(a).parent.element,YAHOO.util.Dom.addClass(a,c))):menuItemsToNavBox(b)}function menuItemsToNavBox(a){if(a.submenu&&a.submenu.itemdata){a=a.submenu.itemdata;for(var b=0;b<a.length;b++)a[b].disabled||addMenuOpToNavBox(a[b])}}
function ensureNavBoxOps(a,b){a||(b||(b=getNavBoxMenuId()),a=document.getElementById(b));if(!a){var c=getNavBoxOperationsDiv();a=document.createElement("ul");a.id=b;YAHOO.util.Dom.addClass(a,"tightMargin");c.appendChild(a);enableNavBox()}return a}function getNavBoxMenuId(){var a=getTypeObjectPage().gene?"gene":getTypeObjectPage().type;return stringTypeToType(a)+"Menu"}function getNavBoxOperationsDiv(){return document.getElementById("navBoxOps")}
function enableNavBox(){populateNavBoxTitle();var a=document.getElementById("navBox");a.style.display="block";adjustForNavBoxWidth();var b=!1,c=document.getElementById("pathwayToolsMenubar"),d=YAHOO.util.Dom.getY(c)+c.offsetHeight;window.onscroll=function(){!b&&0>a.offsetTop-window.pageYOffset?(a.style.top=0,a.style.position="fixed",b=!0):b&&window.pageYOffset<=d&&(a.style.position="absolute",a.style.top=d+"px",b=!1)};getHideNavBoxCookie()&&hideNavBox()}
function showNavBox(){document.getElementById("navBoxBody").style.display="block";document.getElementById("navBoxExpanded").style.display="block";document.getElementById("navBoxCollapsed").style.display="none";setHideNavBoxCookie(!1)}function hideNavBox(){document.getElementById("navBoxBody").style.display="none";document.getElementById("navBoxExpanded").style.display="none";document.getElementById("navBoxCollapsed").style.display="block";setHideNavBoxCookie(!0)}
function setHideNavBoxCookie(a){var b=new Date;b.setDate(b.getDate()+2);set_cookie("hideNavbox",a?1:0,b)}function getHideNavBoxCookie(){var a=get_cookie("hideNavbox");return a?1==a:mobileP()}function adjustForNavBoxWidth(){var a=document.getElementById("navBox"),b=YAHOO.util.Dom.getElementsByClassName("pageContentDynamic","div")[0];b&&(b.style.paddingRight=YAHOO.util.Dom.getViewportWidth()-YAHOO.util.Dom.getX(a)+15+"px")}
function addMenuOpToNavBox(a,b){if(!a.disabled){b=ensureNavBoxOps(b);var c=findMatchingSubmenu(b,a);if(c)if(a.submenu&&a.submenu.itemdata)for(var d=a.submenu.itemdata,e=0;e<d.length;e++)d[e].disabled||addMenuOpToNavBox(d[e],c);else(a.url||a.onclick)&&addMenuOpToNavBox(a,c);else{c=document.createElement("li");d=document.createTextNode(a.text);a.beginning?b.insertBefore(c,b.firstChild):b.appendChild(c);a.id&&(c.id=a.id);if(a.url||a.onclick){YAHOO.util.Dom.addClass(c,a.classname||"navBoxLink");var f=
document.createElement("a");f.appendChild(d);f.title=a.tooltip||a.text;f.href=a.url||"#";a.onclick&&(f.href="#",f.onclick=a.onclick.fn||a.onclick);a.target&&(f.target=a.target);c.appendChild(f)}else if(a.submenu){f=document.createElement("div");e=document.createElement("span");f=document.createElement("div");e.appendChild(d);f.appendChild(e);f.title=a.tooltip||a.text;c.appendChild(f);var g=document.createElement("ul");a.submenu.id&&(g.id=a.submenu.id);if(a.submenu.itemdata)for(d=a.submenu.itemdata,
e=0;e<d.length;e++)d[e].disabled||addMenuOpToNavBox(d[e],g);g.hasChildNodes()?(c.appendChild(g),YAHOO.util.Dom.addClass(f,a.classname||"navBoxSubmenuHeader"),"EXPANDED"==a.style?(YAHOO.util.Dom.addClass(f,"submenuExpanded"),addMenuToggleBehavior(f,g)):"COLLAPSED"==a.style&&(g.style.display="none",YAHOO.util.Dom.addClass(f,"submenuCollapsed"),addMenuToggleBehavior(f,g))):b.removeChild(c)}else c.appendChild(d),a.classname&&YAHOO.util.Dom.addClass(c,a.classname);adjustForNavBoxWidth()}}}
function findMatchingSubmenu(a,b){var c=b.menuId;!c&&b.submenu&&(c=b.id);if(c)return findNavboxUlElt(c,a)}function findNavboxUlElt(a,b){var c=document.getElementById(a);if(c&&(!b||b==c||c.compareDocumentPosition(b)&8)&&(c=c.getElementsByTagName("UL")))return c[0]}function addMenuToggleBehavior(a,b){YAHOO.util.Event.addListener(a,"click",function(){navBoxMenuToggle(a,b)})}
function navBoxMenuToggle(a,b){"none"==b.style.display?(b.style.display="block",YAHOO.util.Dom.replaceClass(a,"submenuCollapsed","submenuExpanded")):(b.style.display="none",YAHOO.util.Dom.replaceClass(a,"submenuExpanded","submenuCollapsed"))}
function populateNavBoxTitle(){var a=getTypeObjectPage();a.title?(a.prefix&&(document.getElementById("objtypeNavBox").innerHTML=a.prefix+":"),document.getElementById("objnameNavBox").innerHTML=a.title):document.getElementById("navBoxTitle").style.display="none"}function mobileP(){return/iPhone|iPad|iPod|Android/i.test(navigator.userAgent)}var cookie_js_version="Version 3.1S",TheCookie;
function Cookie_read_parse_cookie(){var a=document.cookie;if(""==a)return null;for(var a=a.split("; "),b=0,c=0;c<a.length;c++){var d=a[c].indexOf("=");if(-1!=d){var e=a[c].substring(0,d),d=a[c].substring(d+1);"expires"==e?this.expires=d:(b++,this.names[b]=e,this.values[b]=d,this.lookup[e]=d)}}this.count=b}
function writePersistentCookie(a,b,c,d){var e=new Date;d/=1;switch(c.toLowerCase()){case "years":c=e.getYear();1E3>c&&(c+=1900);e.setYear(c+d);break;case "months":e.setMonth(e.getMonth()+d);break;case "days":e.setDate(e.getDate()+d);break;case "hours":e.setHours(e.getHours()+d);break;case "minutes":e.setMinutes(e.getMinutes()+d);break;default:alert("Invalid periodType parameter for writePersistentCookie()")}document.cookie=escape(a)+"="+escape(b)+"; expires="+e.toGMTString()+"; path=/"}
function getCookieValue(a){a=RegExp(escape(a)+"=([^;]+)");return a.test(document.cookie+";")?(a.exec(document.cookie+";"),unescape(RegExp.$1)):!1}function testSessionCookie(){document.cookie="testSessionCookie=Enabled";return"Enabled"==getCookieValue("testSessionCookie")?!0:!1}function testPersistentCookie(){writePersistentCookie("testPersistentCookie","Enabled","minutes",1);return"Enabled"==getCookieValue("testPersistentCookie")?!0:!1}
function deleteCookie(a){getCookieValue(a)&&writePersistentCookie(a,"Pending delete","years",-1);return!0}function Cookie_Save(){var a=new Date;a.setTime(a.getTime()+10368E6);for(var a="expires="+a.toGMTString(),b="",c=1;c<=this.count;c++)b=this.names[c]+"="+this.values[c]+"; ",document.cookie=b+a+"; path=/"}function Cookie_Session_Save(){var a="";Cookie_Wipe();for(var b=1;b<=this.count;b++)a=this.names[b]+"="+this.values[b]+"; path=/; ",document.cookie=a}
function Cookie_Wipe(){var a=new Date;a.setTime(a.getTime()-10368E6);for(var a="expires="+a.toGMTString(),b="",c=1;c<=this.count;c++)b=this.names[c]+"="+this.values[c]+"; path=/; ",document.cookie=b+a}function Cookie_findindex(a){for(var b=1;b<=this.count;b++)if(this.names[b]==a)return b;return 0}function Cookie_Add(a,b){var c;(c=this.findindex(a))||(this.count++,c=this.count,this.names[c]=a);this.values[c]=b;this.lookup[a]=b}
function Cookie(){this.names=[];this.values=[];this.lookup=[];this.expires=this.count=0;this.read_parse_cookie=Cookie_read_parse_cookie;this.Save=Cookie_Save;this.Session_Save=Cookie_Session_Save;this.findindex=Cookie_findindex;this.Add=Cookie_Add;this.read_parse_cookie()}TheCookie=new Cookie;var myargs={};
function getArgs(){for(var a=location.search.substring(1).split("&"),b=0;b<a.length;b++){var c=a[b].indexOf("=");if(-1!=c){var d=a[b].substring(0,c),c=a[b].substring(c+1);myargs[d]=unescape(c)}}return myargs}function initLogin(){if(void 0!=window.userAccountsEnabled&&userAccountsEnabled)initLoginPopup();else try{hideLogin()}catch(a){}}
function initLoginPopup(){getArgs();"undefined"!=typeof myargs.logmsg&&("wrongpw"==myargs.logmsg?ShowPasswordIncorrect():"wrongemail"==myargs.logmsg?ShowEmailNotFound():"emailsent"==myargs.logmsg&&ShowEmailSent(),UnhideLogin())}function UnhideWhyLogin(){var a=document.getElementById("WhyLogin");a.style.visibility="visible";a.style.display="block"}function HideWhyLogin(){var a=document.getElementById("WhyLogin");a.style.visibility="hidden";a.style.display="none"}
function UnhideLogin(){var a=document.getElementById("Login");a.style.visibility="visible";a.style.display="block";$("lmsg").update("");SetURL();a.pleaseHideMeFlag=!1;document.getElementById("emailname").focus()}function pleaseHideLogin(){document.getElementById("Login").pleaseHideMeFlag&&HideLogin()}function HideLogin(){document.getElementById("Login").style.visibility="hidden";ClearThirdPanel();document.getElementById("frmSignon").action="try-login.html"}
function ClearThirdPanel(){document.getElementById("ThirdPanel").innerHTML="";document.getElementById("LogInButton").value="Log In";document.getElementById("FirstRow").style.display="";document.getElementById("SecondRow").style.display="";document.getElementById("ThirdRow").style.display="";document.getElementById("FourthRow").style.display="";document.getElementById("emailname").value="";document.getElementById("password").value=""}
function ShowEmailSent(){document.getElementById("ThirdPanel").innerHTML="An email has been sent with<br>your login information."}function ShowEmailNotFound(){document.getElementById("ThirdPanel").innerHTML="<font color='red'>Email address not found.  Please<br>try again or create a new account.</font>"}function ShowPasswordIncorrect(){document.getElementById("ThirdPanel").innerHTML="<font color='red'>Password incorrect.&nbsp;Please&nbsp;try&nbsp;again.</font>"}
function ForgotPasswordize(){document.getElementById("LogInButton").value="Submit";document.getElementById("ThirdPanel").innerHTML="<b>Forgot your password?</b><br><br>Enter your account's<br>email address:<br><input  name='f_email_name' style='' size='29' tabindex='1'>";document.getElementById("FirstRow").style.display="none";document.getElementById("SecondRow").style.display="none";document.getElementById("ThirdRow").style.display="none";document.getElementById("FourthRow").style.display="none"}
function SetURL(){document.getElementById("myurl").value=document.location}
function xmlhttpGet(a,b,c,d){var e=!1;window.XMLHttpRequest?e=new XMLHttpRequest:window.ActiveXObject&&(e=new ActiveXObject("Microsoft.XMLHTTP"));if(e){if(d)return e.open("GET",a,!1),e.send(b),c(e.responseText);e.open("GET",a,!0);e.onreadystatechange=function(){4==e.readyState&&c(e.responseText)};e.send(b)}else this.alertedAjax||(alert("Your browser does not support Ajax. This webpage will partially work."),this.alertedAjax=!0)}
function popupWaitMsg(a,b,c){var d=new YAHOO.widget.Panel("msgPopup",{width:"400px",constraintoviewport:!0,fixedcenter:!0,underlay:"shadow",close:!1,zindex:2E3});d.setHeader("Please Wait...");d.setBody("Your request is being processed.  This is a computationally intensive operation and may take several minutes or more.  Please be patient.  Please do not resubmit your request while you are waiting.");b&&d.setHeader(b);a&&d.setBody(a);d.render();0<c&&setTimeout(function(){d.hide()},1E3*c);return d}
function popupShortWaitMsg(){popupWaitMsg("Please wait while this page is being generated, which may take a minute or more.")}function popupQueryWaitMsg(){popupWaitMsg("Please wait while your query is being processed.")}function trimWhitespace(a){return a.replace(/^\s*/,"").replace(/\s*$/,"")}var multiorg_initiallySelected,multiorg_availableOrgids,multiorg_unavailableOrgids,multiorg_boldOrgids,multiorg_legend,multiorg_maxOrgs,multiorg_allowClasses;YAHOO.namespace("multi");
YAHOO.multi.initialized=!1;YAHOO.multi.savedOrglistsLoaded=!1;var multiorg_storeOnExit=!0;YAHOO.multi.savedOrglists=[];YAHOO.multi.organisms=[];function showMultiorgChooser(){initMultiorgChooser();clearMultiAC();multiorg_initiallySelected=getOrglistArray();YAHOO.multi.chooser.center();YAHOO.multi.chooser.show()}
function initMultiorgChooser(){if(!YAHOO.multi.initialized){YAHOO.util.Dom.get("multiorgSelectorDialog").style.display="block";withSavedOrglistsLoaded(populateSavedOrglistContainers);initMultiSelectOrganisms();var a=YAHOO.multi.organisms.length;multiorg_initiallySelected&&addOrgids(multiorg_initiallySelected);10>=a?YAHOO.util.Dom.get("multiorgCentercontent").style.visibility="hidden":updateNumOrgs(multiorg_initiallySelected?a-multiorg_initiallySelected.length:a,"","multiorgnum");multiorganismSelectorAC();
buildMultiOrgSelectorTaxTree();initMultiOrgTaxAC();YAHOO.multi.tabs=new YAHOO.widget.TabView("multiorgSelectorTabs");multiorg_legend&&0<multiorg_legend.length&&(document.getElementById("legend").innerHTML=multiorg_legend);YAHOO.multi.initialized=!0}}var onMultiorgSelectorOK=new YAHOO.util.CustomEvent("onMultiorgSelectorOK",this,!1,YAHOO.util.CustomEvent.FLAT);
YAHOO.util.Event.onContentReady("multiorgSelectorDialog",function(){YAHOO.multi.chooser=new YAHOO.widget.Dialog("multiorgSelectorDialog",{buttons:[{text:"OK",handler:function(){var a=getOrglistArray();multiorg_storeOnExit&&storeSelectedOrgs(a);onMultiorgSelectorOK.fire(a);this.hide()},isDefault:!0},{text:"Cancel",handler:function(){deleteMultiorgOptions(!0);addOrgids(multiorg_initiallySelected);this.cancel()}}],visible:!1,fixedcenter:!1,draggable:!0,dragOnly:!0,zIndex:1E3});YAHOO.multi.chooser.render();
YAHOO.multi.chooser.center();YAHOO.multi.chooser.beforeShowEvent.subscribe(initMultiorgChooser)});
function multiorganismSelectorAC(){var a=new YAHOO.util.FunctionDataSource(searchNamesRemoveDuplicates),b=new YAHOO.widget.AutoComplete("multiorgInput","multiorgContainer",a);YAHOO.multi.AC=b;b.alwaysShowContainer=!0;b.animVert=!1;b.autoHighlight=!1;b.suppressInputUpdate=!0;b.typeAheadDelay=1;b.minQueryLength=0;b.maxResultsDisplayed=YAHOO.multi.organisms.length;b.formatResult=function(a,b,e){a=orgIDFromOrgName(a);return isBold(a)?"<b>"+e+"</b>":e};b.itemSelectEvent.subscribe(function(a,b){addNewSelectedOrgFromAC(b[2][0])});
b.dataRequestEvent.subscribe(function(a,d){b.typeAhead=0<d[1].length});b.dataReturnEvent.subscribe(function(a,b){0==b[2].length?YAHOO.util.Dom.get("orgContainer").style.display="none":YAHOO.util.Dom.get("orgContainer").style.display="block";updateNumOrgs(b[2].length,b[1],"multiorgnum")});return{oDS:a,oAC:b}}function searchNamesRemoveDuplicates(a){a=searchNamesAndTags(a,YAHOO.multi.organisms);for(var b=[],c=0;c<a.length;c++){var d=a[c];findNameInCurrentSelection(d)||(b[b.length]=d)}return b}
function findNameInCurrentSelection(a){for(var b=orgListEl().options,c=0;c<b.length;c++)if(a==b[c].text)return!0;return!1}var fnSubscriberMultiorgScroller=function(a,b){var c=b[0].letter;clearMultiAC();var d=YAHOO.util.Dom.get("multiorgContainer"),c=getPositionOfFirstEntryForLetter(c,d,YAHOO.multi.organisms);d.childNodes[0].scrollTop=c};onAlphabetListClick.subscribe(fnSubscriberMultiorgScroller);
function initMultiOrgTaxAC(){initTaxAC(YAHOO.multi.taxtree,"multiorgTaxName","multiorgTaxContainer","multiorgTaxTreeContainer")}function scrollToTaxNode(a,b){var c=document.getElementById(b),d=c.offsetParent,e=c.offsetTop,f=a.getEl().offsetTop;f>d.offsetHeight&&(c.scrollTop=f-e)}
function buildMultiOrgSelectorTaxTree(){YAHOO.multi.taxtree=new YAHOO.widget.TreeView("multiorgSelectorTaxTree");var a=YAHOO.multi.taxtree;a.setDynamicLoad(loadMultiorgTaxSubclasses,1);var b=a.getRoot(),b=new YAHOO.widget.TextNode({id:"TAX-1",label:"All"},b,!1);a.setNodesProperty("propagateHighlightUp",!0);a.setNodesProperty("propagateHighlightDown",!1);a.subscribe("highlightEvent",propagateNodeHighlight);a.subscribe("clickEvent",a.onEventToggleHighlight);b.expand();a.render()}
function loadMultiorgTaxSubclasses(a,b){YAHOO.util.Connect.asyncRequest("GET","/ajax-pgdb-taxon-subs?object="+a.data.id,{success:function(b){var d=eval("("+b.responseText+")");if(d&&d.length&&YAHOO.lang.isArray(d))for(var e=0,f=d.length;e<f;e++){var g=d[e],h;h=new YAHOO.widget.TextNode(g,a,!1);h.data=g;h.title=g.doc;h.propagateHighlightUp=!0;h.propagateHighlightDown=!1;h.highlightState=1==a.highlightState?1:0;g.isClass?(h.label=g.label+" ("+g.numInstances+")",h.isLeaf=!1,h.renderHidden=!0,"TAX-1"==
a.data.id&&h.expand()):(h.isLeaf=!0,isBold(g.id)?h.labelStyle="bold-treenode":includeOrgid(g.id)||(h.enableHighlight=!1,h.propagateHighlightUp=!1,h.labelStyle="disabled-treenode"))}b.argument.fnLoadComplete()},argument:{node:a,fnLoadComplete:b},timeout:14E3})}function propagateNodeHighlight(a){for(var b=0;b<a.children.length;b++){var c=a.children[b];c.highlightState=a.highlightState;c._setHighlightClassName();c.isLeaf||propagateNodeHighlight(c)}}
function orgListEl(){return document.getElementById("multiorgSelection")}function addNewSelections(){var a=YAHOO.multi.tabs.get("activeIndex");0==a?addNewSelectedOrgFromAC():1==a?addNewSelectedOrgsFromTree(YAHOO.multi.taxtree,!0):2==a&&addNewSelectedOrgsFromTree(YAHOO.multi.orglistTree)}function findInOptionList(a,b){for(var c=0;c<b.length;c++){var d=b[c];if(a==d.value)return d}}
function addOption(a,b,c,d){if(!findInOptionList(b,c)){var e=createOption(a,b);d&&isBold(b)&&(e.style.fontWeight="bold");for(b=0;b<c.length&&c.options[b].text<a;)b++;b<c.length?c.add(e,c.options[b]):c.options[b]=e}}function createOption(a,b){var c=document.createElement("option");c.text=a;c.value=b;return c}function addMultiOrgListOption(a,b){var c=orgListEl();okToAddOrg(b,!1)&&(addOption(a,b,c,!0),updateMultiNumSelected())}
function deleteMultiorgOptions(a){for(var b=orgListEl(),c=b.length-1;0<=c;c--)(a||b.options[c].selected)&&b.remove(c);updateMultiNumSelected();clearMultiAC()}function updateMultiNumSelected(){document.getElementById("multiNumSelected").innerHTML=orgListEl().length}function clearMultiAC(){YAHOO.util.Dom.get("multiorgInput").value="";YAHOO.multi.AC.sendQuery("")}
function addNewSelectedOrgFromAC(a){a||(a=trimWhitespace(YAHOO.util.Dom.get("multiorgInput").value));var b=orgIDFromOrgName(a);b&&includeOrgid(b)&&okToAddOrg(b,!0)&&addMultiOrgListOption(a,b);YAHOO.multi.AC.sendQuery(YAHOO.util.Dom.get("multiorgInput").value)}function doWhen(a,b,c){a()?b():setTimeout(doWhen,c,a,b,c)}
function expandAllChildren(a){var b=1==a.highlightState?1:0;a.expand();doWhen(function(){return a.dynamicLoadComplete},function(){for(var c=0;c<a.children.length;c++)a.children[c].highlightState=b,expandAllChildren(a.children[c])},20)}
function expandTreePath(a,b,c){for(var d=b.shift(),e=!1,f=0;f<a.children.length;f++){var g=a.children[f];if(g.data.id==d||g.data.taxId==d)e=g}e&&(e.focus(),0==b.length?(scrollToTaxNode(e,c),e.focus()):(e.expand(),doWhen(function(){return e.dynamicLoadComplete},function(){expandTreePath(e,b,c)})))}function getHighlightedNonLoaded(a){return a.getNodesBy(function(a){if(1==a.highlightState&&!a.isLeaf&&a.isDynamic()&&!a.dynamicLoadComplete)return!0})}
function addNewSelectedOrgsFromTree(a,b){if(b&&multiorg_allowClasses)addHilitTaxa(a);else{var c=getHighlightedNonLoaded(a);if(c){for(var d=!0,e=0,f=0;f<c.length;f++)e+=c[f].data.numInstances||1;multiorg_maxOrgs&&e>multiorg_maxOrgs?(alert("You may not select more than "+multiorg_maxOrgs+" databases."),d=!1):300<e&&!confirm("You are about to retrieve and select a large number of organisms, which could take a substantial amount of time.  Are you sure you wish to continue?")&&(d=!1);if(d){for(var g=popupWaitMsg("Loading Taxonomy Tree..."),
f=0;f<c.length;f++)expandAllChildren(c[f]);setTimeout(doWhen,20,function(){return!getHighlightedNonLoaded(a)},function(){g.hide();addHilitOrgs(a)},20)}}else addHilitOrgs(a)}}function addHilitOrgs(a){var b=a.getNodesBy(function(a){if(a.isLeaf&&a.enableHighlight&&1==a.highlightState)return!0});if(b){for(var c=!0,d=0;d<b.length;d++){var e=b[d];c&&(c=okToAddOrg(e.data.id,c))&&addMultiOrgListOption(e.data.label,e.data.id)}a.getRoot().unhighlight()}}
function addHilitTaxa(a){a=a.getRoot();addHilitTaxaFromNode(a);a.unhighlight()}function addHilitTaxaFromNode(a){if(a.enableHighlight&&0<a.highlightState&&!findInOptionList(a.data.id,orgListEl().options))if(1==a.highlightState)addMultiOrgListOption(a.data.label,a.data.id);else if(!a.isLeaf&&2==a.highlightState)for(var b=0;b<a.children.length;b++)addHilitTaxaFromNode(a.children[b])}
function withSavedOrglistsLoaded(a){var b={success:function(b){YAHOO.multi.savedOrglists=eval("("+b.responseText+")");YAHOO.multi.savedOrglistsLoaded=!0;a()}};YAHOO.multi.savedOrglistsLoaded?a():YAHOO.util.Connect.asyncRequest("GET","/ajax-get-orglist-names",b)}
function getPresentOrgidsAndShowChooser(a,b,c,d,e){a="/"+c+"/ajax-get-containing-orgids?type="+b+"&object="+a;var f;b={success:function(a){a=eval("("+a.responseText+")");0<a.length&&(d?multiorg_boldOrgids=a:(multiorg_unavailableOrgids=!1,multiorg_availableOrgids=a),e&&(multiorg_legend=(multiorg_legend||"")+" "+e));YAHOO.multi.presentOrgidsLoaded=!0;f.hide();showMultiorgChooser()},failure:function(a){f.hide();showMultiorgChooser()},timeout:15E3};YAHOO.multi.presentOrgidsLoaded?showMultiorgChooser():
(f=popupWaitMsg("Loading Organisms..."),YAHOO.util.Connect.asyncRequest("GET",a,b))}
function populateSavedOrglistContainers(){var a=YAHOO.multi.savedOrglists;a&&a.sort(caseInsensitiveOrgListSortByNameFn);BuildSavedOrglistTree();var b=YAHOO.util.Dom.getElementsByClassName("requiresSavedOrglist","span"),c=YAHOO.util.Dom.getElementsByClassName("requiresNoSavedOrglist","span");if(a&&0<a.length){for(var d=YAHOO.util.Dom.getElementsByClassName("savedOrglistSelectEl"),e=0;e<d.length;e++)for(var f=d[e],g=0;g<a.length;g++){var h=a[g];addOption(h.name,h.id,f)}YAHOO.util.Dom.setStyle(b,"display",
"block");YAHOO.util.Dom.setStyle(c,"display","none")}else YAHOO.util.Dom.setStyle(b,"display","none"),YAHOO.util.Dom.setStyle(c,"display","block")}function addOrgids(a){for(var b=0;b<a.length;b++){var c=a[b];if(includeOrgid(c)){var d=orgNameFromOrgID(c);d&&!0==okToAddOrg(c,!0)&&addMultiOrgListOption(d,c)}}}
function getOrglistArray(){var a=[];if(YAHOO.multi.initialized)for(var b=orgListEl(),c=0;c<b.length;c++)0!=b.options[c].value&&(a[a.length]=b.options[c].value);else multiorg_initiallySelected&&(a=multiorg_initiallySelected);return a}
function saveOrglist(a,b){var c=encodeURIComponent(a),d=getOrglistArray(),e=encodeURIComponent(getOrglistStr(d)),c="/ajax-save-orglist?name="+c+"&orgids="+e;b&&(c+="&id="+b);YAHOO.util.Connect.asyncRequest("GET",c,{success:function(b){if("-1"==b.responseText)alert("Save failed.");else{b=b.responseText;var c=!1;YAHOO.multi.savedOrglists||(YAHOO.multi.savedOrglists=[]);for(var e=YAHOO.multi.savedOrglists,k=0;k<e.length;k++)e[k].id==b&&(e[k].orgids=d,c=!0);c||(k=e.length,e[k]={name:a,id:b,orgids:d});
populateSavedOrglistContainers();alert("Organism list "+a+" saved.")}},failure:function(b){alert("Save failed.  Organism list "+a+" not saved.")},timeout:14E3})}function createNamedOrglist(){var a=trimWhitespace(document.getElementById("orglistname").value);0<a.length?saveOrglist(a):alert("You must provide a name for the new database list.")}function updateNamedOrglist(){var a=document.getElementById("savedOrglistUpdate"),a=a.options[a.selectedIndex];saveOrglist(a.text,a.value)}
function initMultiSelectOrganisms(){if(multiorg_availableOrgids||multiorg_unavailableOrgids)for(var a=0;a<allOrganisms.length;a++)includeOrgid(allOrganisms[a].id)&&(YAHOO.multi.organisms[YAHOO.multi.organisms.length]=allOrganisms[a]);else YAHOO.multi.organisms=allOrganisms}
function includeOrgid(a){var b=!1;if(multiorg_unavailableOrgids){for(var c=0;!b&&c<multiorg_unavailableOrgids.length;)multiorg_unavailableOrgids[c]==a&&(b=!0),c++;return!b}if(multiorg_availableOrgids){for(c=0;!b&&c<multiorg_availableOrgids.length;)multiorg_availableOrgids[c]==a&&(b=!0),c++;return b}return!0}function isBold(a){if(multiorg_boldOrgids)for(var b=0;b<multiorg_boldOrgids.length;b++)if(multiorg_boldOrgids[b]==a)return!0;return!1}
function BuildSavedOrglistTree(){var a;if(YAHOO.multi.orglistTree){a=YAHOO.multi.orglistTree;for(var b=a.getRoot(),c=b.children.length;0<c;c--){var d=b.children[c-1];d.data.isStatic||a.removeNode(d,!0)}}else YAHOO.multi.orglistTree=new YAHOO.widget.TreeView("multiorgSavedTree"),a=YAHOO.multi.orglistTree,(c=getRecentlyUsedCookies())&&0<c.length&&addListToTree("Recently Used",c,!0),(c=YAHOO.ptools.popularDatabases)&&0<c.length&&addListToTree("Popular Databases",c,!0),a.setNodesProperty("propagateHighlightUp",
!0),a.setNodesProperty("propagateHighlightDown",!1),a.subscribe("clickEvent",a.onEventToggleHighlight),a.subscribe("highlightEvent",propagateNodeHighlight);if(YAHOO.multi.savedOrglists&&0<YAHOO.multi.savedOrglists.length)for(c=0;c<YAHOO.multi.savedOrglists.length;c++)b=YAHOO.multi.savedOrglists[c],b.orgids?addListToTree(b.name,b.orgids,!1):addUnfetchedListToTree(b.name,b.id);a.render()}
function addListToTree(a,b,c){var d=YAHOO.multi.orglistTree.getRoot();a=new YAHOO.widget.TextNode(a,d,!1);a.data={isStatic:c};a.isLeaf=!1;for(c=0;c<b.length;c++)addOrgidToListTree(a,b[c])}function addOrgidToListTree(a,b){var c=orgNameFromOrgID(b);if(c){var d=new YAHOO.widget.TextNode(c,a,!1);d.data={id:b,label:c};d.isLeaf=!0;isBold(b)?d.labelStyle="bold-treenode":includeOrgid(b)||(d.enableHighlight=!1,d.propagateHighlightUp=!1)}}
function loadOrgidList(a,b){YAHOO.util.Connect.asyncRequest("GET","/ajax-get-orglist-contents?id="+a.data.id,{success:function(b){var d=eval("("+b.responseText+")");if(d&&d.length){for(var e=0;e<d.length;e++)addOrgidToListTree(a,d[e]);for(e=0;e<YAHOO.multi.savedOrglists.length;e++){var f=YAHOO.multi.savedOrglists[e];f.id==a.data.id&&(f.orgids=d)}}b.argument.fnLoadComplete()},argument:{node:a,fnLoadComplete:b},timeout:14E3})}
function addUnfetchedListToTree(a,b){var c=YAHOO.multi.orglistTree.getRoot(),c=new YAHOO.widget.TextNode(a,c,!1);c.data={isStatic:!1,id:b};c.isLeaf=!1;c.setDynamicLoad(loadOrgidList)}function okToAddOrg(a,b){var c=orgListEl();return!multiorg_allowClasses&&multiorg_maxOrgs&&c.length>=multiorg_maxOrgs&&!findInOptionList(a,c.options)?(b&&warnTooManyOrgs(),!1):!0}
function warnTooManyOrgs(){alert("You may not select more than "+multiorg_maxOrgs+" organism databases.  Please delete some selections before attempting to add more.")}function getOrglistStr(a){return"("+a.join(" ")+")"}
function outputSelectedOrgs(a,b,c){b.innerHTML="";if(a&&0<a.length){b.innerHTML="<ul>";for(var d=0;d<a.length;d++){var e=orgNameFromOrgID(a[d]);c&&isBold(a[d])?b.innerHTML+="<li><b>"+e+"</b>":b.innerHTML+="<li>"+e}b.innerHTML+="</ul>"}else b.innerHTML="No organism databases currently selected."}
function outputSelectedOrgsforCrossOrgSearch(a,b,c){b.innerHTML="";if(a&&0<a.length){b.innerHTML="<ul>";for(var d=0;d<a.length;d++){var e=orgNameFromOrgID(a[d]);if(!e)for(var f=0;f<YAHOO.multi.taxtree._nodes.length;f++){var g=YAHOO.multi.taxtree._nodes[f];g&&g.data.id==a[d]&&(e=g.data.label)}c&&isBold(a[d])?b.innerHTML+="<li><b>"+e+"</b>":b.innerHTML+="<li>"+e}b.innerHTML+="</ul>"}else b.innerHTML="ALL organism databases currently selected."}var onChangedOrgsStored=new YAHOO.util.CustomEvent("onChangedOrgsStored");
function storeSelectedOrgs(a){var b="orgids="+getOrglistStr(a);YAHOO.util.Connect.asyncRequest("POST","/ajax-store-biocyc-orgids",{success:function(b){onChangedOrgsStored.fire(a)}},b)}function clearMultiorgSelector(){YAHOO.multi.initialized?deleteMultiorgOptions(!0):multiorg_initiallySelected=[];onMultiorgSelectorOK.fire([])}
function goIfOrgsSelected(a,b){var c=getOrglistArray().length,d=!multiorg_allowClasses&&multiorg_maxOrgs&&c>multiorg_maxOrgs;1<c&&!d?(popupWaitMsg(),location.href=a):(d&&alert("Please select fewer organisms.  The maximum number of organisms this query can handle is "+multiorg_maxOrgs+"."),b&&(onChangedOrgsStored.subscribe(function(){goIfOrgsSelected(a)}),b()))}
function ACNameSelector(a,b,c,d,e,f){e||(e=orgID());e=new YAHOO.util.XHRDataSource(f?"/ajax-frame-search":"/"+e+"/ajax-frame-search");e.responseType=YAHOO.util.XHRDataSource.TYPE_JSON;e.responseSchema={resultsList:"Results",fields:[{key:"id"},{key:"label"},{key:"qName"}]};b=new YAHOO.widget.AutoComplete(a,b,e);b.maxResultsDisplayed=2E3;b.generateRequest=function(a){return"?type="+d+"&max=2000&object="+a+(f?"&orgs="+f:"")+("COMPOUND"==d?"&markclasses=t":"")};b.formatResult=function(a,b,c){return a[2]};
c&&(b.itemSelectEvent.subscribe(function(b,d){var e=d[2];c.value=e[0];a.value=e[1]}),b.textboxKeyEvent.subscribe(function(a,b){c.value=""}));return{oDS:e,oAC:b}}function SVGInit(){var a=YAHOO.util.Dom.getElementsByClassName("psvg"),b=getTypeObjectPage().type,c=!0;"reaction"==stringTypeToType(b)&&(c=!1);for(b=0;b<a.length;b++)hasClassName(a[b],"gsvg")?SVGShrinkToFit(a[b],5,5,!1):SVGShrinkToFit(a[b],20,20,c)}
function SVGShrinkToFit(a,b,c,d){var e=a.getSVGDocument();if(null==e)setTimeout(function(){SVGShrinkToFit(a,b,c,d)},250);else if(e=e.documentElement.getBBox(),0==e.height)setTimeout(function(){SVGShrinkToFit(a,b,c,d)},250);else{var f=get_browser_window_size()[0];a.height=e.height+b;a.width=e.width+c;e=(f-a.width)/2;d&&0<e&&YAHOO.util.Dom.setStyle(a,"margin-left",e+"px")}}function hasClassName(a,b){if(a.className)for(var c=a.className.split(" "),d=0;d<c.length;d++)if(c[d]==b)return!0;return!1}
function popupVideo(a,b){$("msgPopup").innerHTML="";var c=new YAHOO.widget.Panel("msgPopup",{width:"600px",height:"400px",constraintoviewport:!0,fixedcenter:!0,underlay:"shadow",close:!0,zindex:2E3});c.setHeader(b);c.setBody("<iframe type=text/html class='video' frameborder=0 src='"+a+"'/>");c.render();return c};
