
from CellScribe import Metabolite

l_valyl_tRNAval = Metabolite("L_valyl_tRNA(val)", kegg="C02554")
l_leycyl_tRNAleu = Metabolite("L_leucyl_tRNA(leu)", kegg="C02047")
l_isoleucyl_tRNAile = Metabolite("L_isoleucyl_tRNA(ile)", kegg="C03127")
l_lysyl_tRNAlys = Metabolite("L_lysyl_tRNA(lys)", kegg="C01931")
l_arginyl_tRNAarg = Metabolite("L_arginyl_tRNA(arg)", kegg="C02163")
l_prolyl_tRNApro = Metabolite("L_prolyl_tRNA(pro)", kegg="C02702")
l_histidyl_tRNAhis = Metabolite("L_histidyl_tRNA(his)", kegg="C02988")
l_phenylalanyl_tRNAphe = Metabolite("L_phenylalanyl_tRNA(phe)", kegg="C03511")
l_tyrosyl_tRNAtyr = Metabolite("L_tyrosyl_tRNA(tyr)", kegg="C02839")
l_trypophanyl_tRNAtrp = Metabolite("L_tryptophanyl_tRNA(trp)", kegg="C03512")
l_alanyl_tRNAala = Metabolite("L_alanyl_tRNA(ala)", kegg="C00886")
l_glycyl_tRNAgly = Metabolite("L_glycyl_tRNA(gly)", kegg="C02412")
l_threonyl_tRNAthr = Metabolite("L_threonyl_tRNA(thr)", kegg="C02992")
l_seryl_tRNAser = Metabolite("L_seryl_tRNA(ser)", kegg="C02553")
l_methionyl_tRNAmet = Metabolite("L_methionyl_tRNA(met)", kegg="C02430")
l_cysteinyl_tRNAcys = Metabolite("L_cysteinyl_tRNA(cys)", kegg="C03125")
l_asparaginyl_tRNAasn = Metabolite("L_asparaginyl_tRNA(asn)", kegg="C03402")
l_glutamyl_tRNAglu = Metabolite("L_glutamyl_tRNA(glu)", kegg="C02987")
l_aspartyl_tRNAasp = Metabolite("L_aspartyl_tRNA(asp)", kegg="C02984")
